version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    tty: true
    environment:
      - VITE_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/hackathon_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: touka_db
      MYSQL_USER: touka
      MYSQL_PASSWORD: touka
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/init.sql # init.sql をマウント
      - ./seed.sql:/seed.sql # seed.sql をマウント

volumes:
  mysql_data:
